language: perl
perl:
- '5.26'
deploy:
  provider: cloudfiles
  username:
    secure: TxTnm51UkGF2Fel4bp7z6VSRcUY9+ffE0emQbaQ1DU/B4dttTO0jJjhK0EN9uCY/j+TgYY6tBMaA/hmNPxOAtSf3bJa3BMJYx5MI5Fk/wAcNsRZc4smF5G0DBM3G8RIR1Rzbmg9VOcf5exCT5KVKNzj751439w26taaWT8wr0km8u7ATAeHtj25fq7X+SEAweM5+pwXOfElJ+SLHnFXPtVvmJrF7tNFyFpP2uJU/IVVZR/2c2zljV82qTiyk3yYDdQrRijEYJwOHMgHy0btXm/nO9cBT9BKdufEnH8EKZd5QU1tK5sO+/ElMyMTcW28xFzw5n8inpf0Eoc/gkLVhibI2Hdh8pNH6YZS5GIB3AgLVnoio91+xxP6R/LAUS4QPwKbJdPFqHNtobOhNP9eXTrd9iXm2TtODhNFlQIGfyFbF8EKuyoAOMQti9c4SKkBFCvqg/PoU/7RdZ24+WlGOa19yfrSkIz4wtUEhzzgULpbrE38/I1c7Vvyxw+Y8nOEuq2N8M3vWo2Z8LUCa4/AYRll8r0lPRmC4viJcYpTUf+sCGsTVk4laHsS66oiEkdvn8xK+IKvLUxPJkwUV3LPoJenuNc9xot92Ho2zzPo1vbHfF6kriW0BqGFoFRRxKTjkauv8TXVyEEulMZlvcQh44dHkpCDAgwpMvuTaTmxK6io=
  region: IAD
  container: skel-builds
  skip_cleanup: true
  api-key:
    secure: KCo75nxwLR50A02y8Iq5nu6pVBFZnyWudCRNif0CTy7+9OZEEJb2naeMgD4prmBMApjNpf70uwz8I1Svbr1F8lGcJW/hfGn4VIpdYZKLrVYk05JyAkHikwhSsYgA04O/TFIaOVfG3aJjWv/cxP41tBisyaUUnRqig5zGw7ofULylfOz/rb1HktPr+DSl56ncKlPJhXYM8xHhNtikPdY6vbOtqoF1EXc+Uf8rWx54Jr9lAWN+69JiEUcth2rir4J40WxlNurfF+UM6mjoHtgqJ6Hpur7PCSG35ezyXezZhjgvvBVTTIZHWfJYxWFtYtig08opu29detV/w0K/yyGM4U1IHgon5x0KsMNLSXUMWyE053LoJPx1SVrlkZ4JJ/tbvyJYSgyhwgFFW07Z/S8wT2zn8zgD8EmfKtEnGtOyD8bzJEZ9FkyPq3DKtL+BZxfbNqhzVX6rtFllvDVinNrv9usmNZnpijDn13dAEd2uAMROPj5irpNVoe638KYsvVrFsjPo/p64Nf2qCELvv42tMLmSK7xnUnMroxWEE8p4GRMVtKU4QlK85xXBednYiGe86SC/teeiaFgPWmJtLYXPWHsbu0n7NM+BUV8htoCjhWt1zpryH77nsvnbfLmIHX+kWJlfAYj1qc3Wux2Sfu8xMHTJeKu12AjEe4BRKAn78DM=
  on:
    all_branches: true
before_deploy:
 - "echo $TRAVIS_BRANCH > travis-branch"
 - "echo $TRAVIS_COMMIT > travis-commit"
after_deploy:
 - curl -X POST https://skel.atat.codes/deploy/$TRAVIS_COMMIT/$TRAVIS_BRANCH
